inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

require:
  - rubocop-airbnb



AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - '.bundle/**/*'
    - 'Gemfile.lock'

# Project specific overrides
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'bin/soba'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'bin/soba'

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Allow Japanese comments in documentation
Style/AsciiComments:
  Enabled: false

# For CLI application
Style/GlobalVars:
  Exclude:
    - 'bin/soba'

# Disable Rails-specific rules since this is a pure Ruby CLI application, not a Rails app
# These cops are incorrectly triggered by rubocop-airbnb which includes Rails cops,
# but they don't apply to CLI tools that don't have Rails dependencies
Rails/NegateInclude:
  Enabled: false  # Rails/NegateInclude expects Rails-specific !include? => exclude? conversion
                  # In pure Ruby, we use !include? instead of Rails' exclude? method

Rails/Present:
  Enabled: false  # Rails/Present expects Rails-specific .present? method usage
                  # In pure Ruby, we use standard methods like !nil? && !empty? instead

# For RSpec
RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

# This is a Rails-specific cop that doesn't apply to CLI applications
Airbnb/ClassOrModuleDeclaredInWrongFile:
  Enabled: false

# Additional Rails-specific cops that don't apply to pure Ruby CLI applications
# These are ActiveRecord/database-related cops that have no relevance to a CLI tool
Rails/Pluck:
  Enabled: false  # Rails/Pluck is for ActiveRecord query optimization, not applicable to CLI tools

Rails/PluckInWhere:
  Enabled: false  # Rails/PluckInWhere is for ActiveRecord query optimization, not applicable to CLI tools