inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

require:
  - rubocop-airbnb



AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - '.bundle/**/*'
    - 'Gemfile.lock'

# Project specific overrides
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'bin/soba'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'bin/soba'

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Allow Japanese comments in documentation
Style/AsciiComments:
  Enabled: false

# For CLI application
Style/GlobalVars:
  Exclude:
    - 'bin/soba'

# This is not a Rails application
Rails/NegateInclude:
  Enabled: false

# For RSpec
RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

# This is a Rails-specific cop that doesn't apply to CLI applications
Airbnb/ClassOrModuleDeclaredInWrongFile:
  Enabled: false

# Rails-specific cops that don't apply to CLI applications
Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false