# frozen_string_literal: true

require "active_support/core_ext/object/blank"
require "active_support/core_ext/string/exclude"
require "pathname"
require "yaml"
require "io/console"

module Soba
  module Commands
    class Init
      def execute
        puts "🚀 Initializing soba configuration..."
        puts ""

        config_path = Pathname.pwd.join('.osoba', 'config.yml')

        if config_path.exist?
          puts "⚠️  Configuration file already exists at: #{config_path}"
          print "Do you want to overwrite it? (y/N): "
          response = $stdin.gets.chomp.downcase
          if response != 'y' && response != 'yes'
            puts "✅ Configuration unchanged."
            return
          end
        end

        # Collect configuration values
        puts "Let's set up your GitHub configuration:"
        puts ""

        # GitHub repository - auto-detect from git remote
        default_repo = detect_github_repository

        if default_repo
          print "Enter GitHub repository (format: owner/repo) [#{default_repo}]: "
        else
          print "Enter GitHub repository (format: owner/repo): "
        end

        repository = $stdin.gets.chomp
        if repository.empty? && default_repo
          repository = default_repo
        end

        while repository.blank? || repository.exclude?('/')
          puts "❌ Invalid format. Please use: owner/repo"
          print "Enter GitHub repository: "
          repository = $stdin.gets.chomp
        end

        # GitHub token
        puts ""
        puts "GitHub Personal Access Token (PAT) setup:"
        puts "  1. Use environment variable ${GITHUB_TOKEN} (recommended)"
        puts "  2. Enter token directly (will be visible in config file)"
        print "Choose option (1-2) [1]: "
        token_option = $stdin.gets.chomp
        token_option = '1' if token_option.empty?

        token = if token_option == '2'
                  print "Enter GitHub token: "
                  # Hide input for security
                  $stdin.noecho(&:gets).chomp.tap { puts }
                else
                  '${GITHUB_TOKEN}'
                end

        # Polling interval
        puts ""
        print "Enter polling interval in seconds [20]: "
        interval = $stdin.gets.chomp
        interval = '20' if interval.empty?
        interval = interval.to_i
        interval = 20 if interval <= 0

        # Create configuration
        config = {
          'github' => {
            'token' => token,
            'repository' => repository,
          },
          'workflow' => {
            'interval' => interval,
          },
        }

        # Write configuration file
        config_path.dirname.mkpath
        config_content = <<~YAML
          # soba CLI configuration
          # Generated by: soba init
          # Date: #{Time.now}

          github:
            # GitHub Personal Access Token
            # Can use environment variable: ${GITHUB_TOKEN}
            token: #{config['github']['token']}

            # Target repository (format: owner/repo)
            repository: #{config['github']['repository']}

          workflow:
            # Issue polling interval in seconds
            interval: #{config['workflow']['interval']}
        YAML

        File.write(config_path, config_content)

        puts ""
        puts "✅ Configuration created successfully!"
        puts "📁 Location: #{config_path}"

        # Verify token if environment variable is used
        if token == '${GITHUB_TOKEN}'
          puts ""
          if ENV['GITHUB_TOKEN']
            puts "✅ GITHUB_TOKEN environment variable is set"
          else
            puts "⚠️  GITHUB_TOKEN environment variable is not set"
            puts "   Please set it before running soba commands:"
            puts "   export GITHUB_TOKEN='your-token-here'"
          end
        end

        # Add .osoba to .gitignore if needed
        gitignore_path = Pathname.pwd.join('.gitignore')
        if gitignore_path.exist?
          gitignore_content = File.read(gitignore_path)
          unless gitignore_content.include?('.osoba')
            puts ""
            print "Add .osoba/ to .gitignore? (Y/n): "
            response = $stdin.gets.chomp.downcase
            if response != 'n' && response != 'no'
              File.open(gitignore_path, 'a') do |f|
                f.puts "" unless gitignore_content.end_with?("\n")
                f.puts "# soba configuration directory"
                f.puts ".osoba/"
              end
              puts "✅ Added .osoba/ to .gitignore"
            end
          end
        end

        puts ""
        puts "🎉 Setup complete! You can now use:"
        puts "   soba config     - View current configuration"
        puts "   soba issue list #{config['github']['repository']} - List repository issues"
      rescue Interrupt
        puts "\n\n❌ Setup cancelled."
        exit 1
      rescue StandardError => e
        puts "\n❌ Error: #{e.message}"
        exit 1
      end

      private

      def detect_github_repository
        return nil unless Dir.exist?('.git')

        # Try to get remote origin URL
        remote_url = `git config --get remote.origin.url 2>/dev/null`.chomp
        return nil if remote_url.empty?

        # Parse GitHub repository from various URL formats
        # https://github.com/owner/repo.git
        # git@github.com:owner/repo.git
        # ssh://git@github.com/owner/repo.git
        case remote_url
        when %r{github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?$}
          "#{Regexp.last_match(1)}/#{Regexp.last_match(2)}"
        when %r{^git@github\.com:([^/]+)/([^/]+?)(?:\.git)?$}
          "#{Regexp.last_match(1)}/#{Regexp.last_match(2)}"
        else
          nil
        end
      rescue StandardError
        nil
      end
    end
  end
end