x-logging-minimal: &logging-minimal
  logging:
    driver: json-file
    options:
      max-size: 1m
      max-file: 1

name: ${COMPOSE_PROJECT_NAME}
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    <<: *logging-minimal
