name: Release Binary Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-linux-x64:
    name: Build Linux x64 Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Build with Tebako
        run: |
          ./scripts/build-tebako.sh --platform linux-x64

      - name: Test built binary
        run: |
          ./scripts/build-tebako.sh --test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: soba-linux-x64
          path: dist/soba-linux-x64
          retention-days: 30

  create-release:
    name: Create GitHub Release
    needs: [build-linux-x64]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: soba-linux-x64
          path: dist/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's New

            This release includes a standalone binary build of soba CLI for Linux x64.

            ### Installation

            Download the binary for your platform and make it executable:

            ```bash
            chmod +x soba-linux-x64
            mv soba-linux-x64 /usr/local/bin/soba
            ```

            ### Supported Platforms

            - Linux x64

            ### Notes

            - This binary is built with Tebako and includes Ruby runtime
            - No Ruby installation required on the target system

          draft: false
          prerelease: false

      - name: Upload Release Asset - Linux x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/soba-linux-x64
          asset_name: soba-linux-x64
          asset_content_type: application/octet-stream

  # Future platform builds can be added here
  # build-macos-x64:
  #   name: Build macOS x64 Binary
  #   runs-on: macos-latest
  #   ...

  # build-macos-arm64:
  #   name: Build macOS ARM64 Binary
  #   runs-on: macos-latest
  #   ...

  # build-windows-x64:
  #   name: Build Windows x64 Binary
  #   runs-on: windows-latest
  #   ...